# For detailed configuration reference documentation, visit:
# https://supabase.com/docs/guides/local-development/cli/config

project_id = "open-bsp-api"

[api]
schemas = ["public", "storage", "billing"]

[functions.whatsapp-webhook]
verify_jwt = false
import_map = "./functions/deno.json"
entrypoint = "./functions/whatsapp-webhook/index.ts"

[functions.instagram-webhook]
verify_jwt = false
import_map = "./functions/deno.json"
entrypoint = "./functions/instagram-webhook/index.ts"

[functions.whatsapp-management]
verify_jwt = false
import_map = "./functions/deno.json"
entrypoint = "./functions/whatsapp-management/index.ts"

[functions.instagram-management]
verify_jwt = false
import_map = "./functions/deno.json"
entrypoint = "./functions/instagram-management/index.ts"

[functions.media-preprocessor]
verify_jwt = false
import_map = "./functions/deno.json"
entrypoint = "./functions/media-preprocessor/index.ts"

[functions.agent-client]
verify_jwt = false
import_map = "./functions/deno.json"
entrypoint = "./functions/agent-client/index.ts"

[functions.whatsapp-dispatcher]
verify_jwt = false
import_map = "./functions/deno.json"
entrypoint = "./functions/whatsapp-dispatcher/index.ts"

[functions.campaign-worker]
verify_jwt = false
import_map = "./functions/deno.json"
entrypoint = "./functions/campaign-worker/index.ts"

[functions.instagram-dispatcher]
verify_jwt = false
import_map = "./functions/deno.json"
entrypoint = "./functions/instagram-dispatcher/index.ts"

[functions.mcp]
verify_jwt = false
import_map = "./functions/deno.json"
entrypoint = "./functions/mcp/index.ts"

[functions.storage-gc]
verify_jwt = false
import_map = "./functions/deno.json"
entrypoint = "./functions/storage-gc/index.ts"

[functions.chatbot-management]
verify_jwt = false
import_map = "./functions/deno.json"
entrypoint = "./functions/chatbot-management/index.ts"

[functions.chatbot-reply-webhook]
verify_jwt = false
import_map = "./functions/deno.json"
entrypoint = "./functions/chatbot-reply-webhook/index.ts"
