-- Generated by Supabase db diff (pg-schema engine) from schema sources.
-- Removed unrelated baseline trigger-function drift and spurious table REVOKEs.
-- Function ACLs are copied from schema sources; pg-schema omits function grants.
set check_function_bodies = off;

CREATE OR REPLACE FUNCTION public.begin_node_conversation_operation(p_organization_id uuid, p_conversation_id uuid, p_request_id uuid, p_action text, p_observed_last_inbound_wamid text, p_expected_revision text)
 RETURNS chatbot_node_operations
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO ''
AS $function$
declare
  target public.conversations;
  mapping public.chatbot_node_conversations;
  actor uuid;
  role public.role;
  latest_wamid text;
  operation public.chatbot_node_operations;
  body jsonb;
begin
  if auth.uid() is null or p_action not in ('resolve-and-close','resume','takeover') then
    raise exception 'authenticated conversation action required' using errcode = '42501'; end if;
  select * into target from public.conversations where organization_id = p_organization_id and id = p_conversation_id for update;
  actor := public.get_current_human_agent_id(p_organization_id);
  role := public.get_request_organization_role(p_organization_id);
  if target.id is null or actor is null or role not in ('owner','admin','supervisor','agent')
    or (role = 'agent' and (p_action = 'resume' or (target.assigned_agent_id is distinct from actor
      and not (p_action = 'takeover' and target.assigned_agent_id is null and target.routing_queue_id is not null
        and exists(select 1 from public.routing_queue_members where organization_id = p_organization_id and routing_queue_id = target.routing_queue_id and agent_id = actor))))) then
    raise exception 'conversation action is not permitted' using errcode = '42501'; end if;
  body := jsonb_build_object('observed_last_inbound_wamid',p_observed_last_inbound_wamid,
    'expected_revision',p_expected_revision,'actor_agent_id',actor);
  select * into operation from public.chatbot_node_operations where request_id = p_request_id;
  if found then
    if operation.organization_id <> p_organization_id or operation.conversation_id is distinct from p_conversation_id
      or operation.action <> p_action or operation.payload - 'node_conversation_id' <> body then
      raise exception 'request ID cannot be reused with different data' using errcode = '23514'; end if;
    if operation.status <> 'failed' then return operation; end if;
  end if;
  select * into mapping from public.chatbot_node_conversations where organization_id = p_organization_id and conversation_id = p_conversation_id for update;
  if not found or (case when p_action = 'takeover' then mapping.human_owned or mapping.support_request->>'status' is distinct from 'waiting' else not mapping.human_owned end)
    or target.status <> 'active' or not public.is_organization_active(p_organization_id) then
    raise exception 'conversation is not in active human support' using errcode = '23514'; end if;
  if p_expected_revision !~ '^[0-9]+$' or p_expected_revision::numeric < mapping.ownership_revision::numeric
    or (p_action = 'takeover' and p_expected_revision::numeric <> mapping.ownership_revision::numeric) then
    raise exception 'conversation ownership changed' using errcode = '40001'; end if;
  if p_action='takeover' and role='agent' and
    (public.business_hours_status(p_organization_id,target.routing_queue_id)->>'open')::boolean is not true then
    raise exception 'Support is outside business hours. A manager can override the schedule.' using errcode='23514';
  end if;
  latest_wamid := mapping.last_inbound_wamid;
  if latest_wamid is null then
    select external_id into latest_wamid from public.messages where organization_id = p_organization_id and conversation_id = p_conversation_id
      and direction = 'incoming' and external_id is not null order by created_at desc, id desc limit 1;
  end if;
  if p_action <> 'takeover' and latest_wamid is distinct from p_observed_last_inbound_wamid then
    raise exception 'A new customer message arrived—review it before closing.' using errcode = '40001'; end if;
  if exists(select 1 from public.messages m join public.agents a on a.id = m.agent_id where m.conversation_id = target.id
    and m.direction = 'outgoing' and not a.ai and m.status ? 'pending' and not m.status ?| array['sent','delivered','read','failed']) then
    raise exception 'Wait for pending human messages to finish sending.' using errcode = '23514'; end if;
  if exists(select 1 from public.chatbot_node_operations where organization_id = p_organization_id
    and organization_address = mapping.organization_address and status not in ('succeeded','failed')
    and (conversation_id is null or conversation_id = target.id)) then
    raise exception 'conversation has an unresolved bridge operation' using errcode = '23514'; end if;
  if operation.request_id is not null then
    -- Manual retry reclaims ownership and its durable operation atomically, with
    -- exactly the same access/message/send checks as the original request.
    update public.chatbot_node_operations set status='reconciling',attempts=0,next_attempt_at=null
      where request_id=p_request_id returning * into operation;
  else
    insert into public.chatbot_node_operations(request_id,organization_id,organization_address,conversation_id,action,phase,payload)
      values(p_request_id,p_organization_id,mapping.organization_address,target.id,p_action,p_action,
        body || jsonb_build_object('node_conversation_id',mapping.node_conversation_id)) returning * into operation;
  end if;
  if p_action = 'takeover' and target.assigned_agent_id is distinct from actor then
    -- Manager override can claim a queued chat without pretending to be a queue
    -- member. The original queue remains in support_request.target for history.
    update public.conversations set assigned_agent_id = actor,
      routing_queue_id = case when role in ('owner','admin','supervisor') and not exists(
        select 1 from public.routing_queue_members where organization_id=p_organization_id
          and routing_queue_id=target.routing_queue_id and agent_id=actor) then null else routing_queue_id end
      where id = target.id;
  end if;
  update public.chatbot_node_conversations set pending_request_id = p_request_id, lifecycle_enabled = true,
    last_inbound_wamid = latest_wamid where organization_id = p_organization_id and conversation_id = target.id;
  return operation;
end;
$function$
;

CREATE OR REPLACE FUNCTION public.business_hours_schedule_open(p_schedule jsonb, p_at timestamp with time zone)
 RETURNS boolean
 LANGUAGE plpgsql
 STABLE
 SET search_path TO ''
AS $function$
declare local_at timestamp; r jsonb; day_name text;
begin
  if p_schedule is null or p_schedule='null'::jsonb or p_schedule->>'enabled'='false' then return true; end if;
  local_at := p_at at time zone (p_schedule->>'timezone');
  select value into r from jsonb_array_elements(coalesce(p_schedule->'holidays','[]'::jsonb))
    where value->>'date'=to_char(local_at,'YYYY-MM-DD');
  if found then
    if (r->>'closed')::boolean then return false; end if;
  elsif p_schedule->>'mode'='all_days' then r := p_schedule->'all_days';
  else
    day_name := (array['monday','tuesday','wednesday','thursday','friday','saturday','sunday'])[extract(isodow from local_at)::integer];
    r := p_schedule->'per_day'->day_name;
    if r->>'enabled' is distinct from 'true' then return false; end if;
  end if;
  -- Lexical HH:mm comparisons keep 24:00 as the next-day boundary.
  return coalesce(to_char(local_at,'HH24:MI') >= r->>'start_time'
    and to_char(local_at,'HH24:MI') < r->>'end_time', false);
exception when others then return false; -- malformed legacy configuration fails closed
end;
$function$
;

CREATE OR REPLACE FUNCTION public.business_hours_status(p_organization_id uuid, p_queue_id uuid DEFAULT NULL::uuid, p_agent_id uuid DEFAULT NULL::uuid, p_at timestamp with time zone DEFAULT now())
 RETURNS jsonb
 LANGUAGE plpgsql
 STABLE SECURITY DEFINER
 SET search_path TO ''
AS $function$
declare root jsonb; schedule jsonb; available_count integer; is_open boolean; enabled boolean;
begin
  select extra->'business_hours' into root from public.organizations where id=p_organization_id;
  enabled := root is not null and root<>'null'::jsonb and root->>'enabled' is distinct from 'false';
  schedule := case when enabled and root->'queue_overrides'->p_queue_id::text is not null
    and root->'queue_overrides'->p_queue_id::text<>'null'::jsonb then root->'queue_overrides'->p_queue_id::text else root end;
  is_open := not enabled or public.business_hours_schedule_open(schedule,p_at);
  select count(*) into available_count from public.agents a
    join public.agent_assignment_presence p on p.organization_id=a.organization_id and p.agent_id=a.id
    where a.organization_id=p_organization_id and not a.ai and a.user_id is not null
      and a.extra->>'role'='agent' and coalesce(a.extra->'invitation'->>'status','accepted')='accepted'
      and p.available and p.last_heartbeat_at >= p_at-interval '2 minutes'
      and (p_agent_id is null or a.id=p_agent_id)
      and (p_queue_id is null or exists(select 1 from public.routing_queue_members m
        join public.routing_queues q on q.id=m.routing_queue_id and q.organization_id=m.organization_id and q.status='active'
        where m.organization_id=p_organization_id and m.agent_id=a.id and m.routing_queue_id=p_queue_id));
  return jsonb_build_object('configured',enabled,'open',is_open,'available_agents',available_count,
    'timezone',schedule->>'timezone','reason',case when not public.is_organization_active(p_organization_id) then 'suspended'
      when not is_open then 'outside_hours' when available_count=0 then 'no_agents' else 'available' end);
end;
$function$
;

CREATE OR REPLACE FUNCTION public.enforce_human_conversation_assignee()
 RETURNS trigger
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO ''
AS $function$
begin
  if new.assigned_agent_id is null then
    return new;
  end if;

  -- Existing owners keep serving customers after the closing boundary.
  -- Managers can explicitly cover an after-hours request; ordinary agent
  -- claims and service-role assignment must respect the effective schedule.
  if (tg_op='INSERT' or new.assigned_agent_id is distinct from old.assigned_agent_id)
    and not (public.business_hours_status(new.organization_id,new.routing_queue_id)->>'open')::boolean
    and coalesce(public.get_request_organization_role(new.organization_id)::text,'') not in ('owner','admin','supervisor') then
    raise exception 'Support is outside business hours. A manager can override the schedule.' using errcode='23514';
  end if;

  if not exists (
    select 1
    from public.agents
    where id = new.assigned_agent_id
      and organization_id = new.organization_id
      and ai = false
      and user_id is not null
  ) then
    raise exception 'Conversation assignee must be a human agent in the same organization'
      using errcode = '23514';
  end if;

  if new.routing_queue_id is not null
    and not exists (
      select 1
      from public.routing_queue_members member
      where member.organization_id = new.organization_id
        and member.routing_queue_id = new.routing_queue_id
        and member.agent_id = new.assigned_agent_id
    )
  then
    raise exception 'Conversation assignee must belong to its routing queue'
      using errcode = '23514';
  end if;

  return new;
end;
$function$
;

CREATE OR REPLACE FUNCTION public.get_business_hours_status(p_organization_id uuid, p_queue_id uuid DEFAULT NULL::uuid)
 RETURNS jsonb
 LANGUAGE plpgsql
 STABLE SECURITY DEFINER
 SET search_path TO ''
AS $function$
begin
  if public.get_request_organization_role(p_organization_id) is null then
    raise exception 'Tenant membership required' using errcode='42501'; end if;
  if p_queue_id is not null and not exists(select 1 from public.routing_queues where organization_id=p_organization_id and id=p_queue_id) then
    raise exception 'Tenant queue required' using errcode='42501'; end if;
  return public.business_hours_status(p_organization_id,p_queue_id);
end;
$function$
;

CREATE OR REPLACE FUNCTION public.guard_business_hours_settings()
 RETURNS trigger
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO ''
AS $function$
declare s jsonb := new.extra->'business_hours'; q record; field text;
begin
  if s is null or s='null'::jsonb then return new; end if;
  if tg_op='UPDATE' and s is not distinct from old.extra->'business_hours' then return new; end if;
  perform public.validate_business_hours_schedule(s);
  if s ? 'queue_overrides' then
    if jsonb_typeof(s->'queue_overrides') <> 'object' then
      raise exception 'Queue overrides must be an object' using errcode='22023'; end if;
    for q in select * from jsonb_each(s->'queue_overrides') loop
      -- JSON merge uses null tombstones to remove an override atomically.
      if q.value='null'::jsonb then continue; end if;
      if not exists(select 1 from public.routing_queues where organization_id=new.id and id=q.key::uuid and status='active') then
        raise exception 'Queue override must belong to an active tenant queue' using errcode='22023'; end if;
      if q.value ? 'queue_overrides' then raise exception 'Nested queue overrides are unsupported' using errcode='22023'; end if;
      perform public.validate_business_hours_schedule(q.value);
    end loop;
  end if;
  foreach field in array array['outside_hours_message','no_agents_message'] loop
    if s ? field and (jsonb_typeof(s->field)<>'string' or length(btrim(s->>field)) not between 1 and 4096) then
      raise exception 'Unavailable support messages must contain 1 to 4096 characters' using errcode='22023'; end if;
  end loop;
  return new;
end;
$function$
;

CREATE OR REPLACE FUNCTION public.notify_support_unavailability(p_conversation_id uuid, p_request_id text, p_agent_id uuid DEFAULT NULL::uuid)
 RETURNS void
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO ''
AS $function$
declare c public.conversations; availability jsonb; root jsonb; body text; latest_inbound timestamptz;
begin
  select * into c from public.conversations where id=p_conversation_id for update;
  if not found or c.status<>'active' or not public.is_organization_active(c.organization_id) then return; end if;
  availability := public.business_hours_status(c.organization_id,c.routing_queue_id,p_agent_id);
  if not (availability->>'configured')::boolean or availability->>'reason' not in ('outside_hours','no_agents') then return; end if;
  select extra->'business_hours' into root from public.organizations where id=c.organization_id;
  body := case when availability->>'reason'='outside_hours' then
    coalesce(root->>'outside_hours_message','Our support team is currently outside business hours. Your request is queued and will be reviewed when support is available.')
    else coalesce(root->>'no_agents_message','All support agents are currently unavailable. Your request is queued for the next available support agent.') end;
  -- Do not originate a free-form notice outside the customer service window.
  select max(timestamp) into latest_inbound from public.messages where conversation_id=c.id and direction='incoming' and content<>'{}'::jsonb;
  if latest_inbound is null or latest_inbound < now()-interval '24 hours' then return; end if;
  insert into public.messages(id,organization_id,conversation_id,direction,service,organization_address,
    group_address,content,timestamp)
  values(md5('support-availability:'||c.id::text||':'||p_request_id)::uuid,c.organization_id,c.id,
    'outgoing',c.service,c.organization_address,c.group_address,
    jsonb_build_object('version','1','type','text','kind','text','text',body),now())
  on conflict(id) do nothing;
end;
$function$
;

CREATE OR REPLACE FUNCTION public.record_node_chatbot_handoff(p_organization_id uuid, p_organization_address text, p_recipient text, p_source_wamid text, p_node_conversation_id text, p_event_id uuid, p_agent_id uuid DEFAULT NULL::uuid, p_routing_queue_id uuid DEFAULT NULL::uuid, p_revision text DEFAULT NULL::text)
 RETURNS uuid
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO ''
AS $function$
declare
  target public.conversations;
  existing_receipt public.chatbot_node_handoff_receipts;
begin
  perform pg_advisory_xact_lock(hashtextextended(p_event_id::text, 117));
  select * into existing_receipt from public.chatbot_node_handoff_receipts where event_id = p_event_id;
  if found then
    if existing_receipt.organization_id <> p_organization_id then
      raise exception 'handoff event belongs to another organization' using errcode = '42501';
    end if;
    return existing_receipt.conversation_id;
  end if;
  if not exists (select 1 from public.organization_lifecycle where organization_id = p_organization_id and status = 'active') then
    raise exception 'organization is archived' using errcode = '42501';
  end if;
  if not exists (select 1 from public.chatbot_node_bridges where organization_id = p_organization_id
    and organization_address = p_organization_address and engine in ('transitioning', 'node')) then
    raise exception 'number is not managed by Node' using errcode = '23514';
  end if;
  -- The exact source message must have arrived; never infer a conversation
  -- from a different number or an older conversation for the same customer.
  select c.* into target from public.conversations c join public.messages m on m.conversation_id = c.id
    where c.organization_id = p_organization_id and c.organization_address = p_organization_address
      and c.contact_address = p_recipient and m.organization_id = p_organization_id
      and m.external_id = p_source_wamid and m.direction = 'incoming' for update of c;
  if not found then raise exception 'source customer message has not arrived' using errcode = '40001'; end if;
  if exists(select 1 from public.chatbot_node_conversations where organization_id = p_organization_id and conversation_id = target.id
    and lifecycle_enabled and (p_revision is null or p_revision::numeric < ownership_revision::numeric
      or (p_revision::numeric = ownership_revision::numeric and not human_owned))) then
    insert into public.chatbot_node_handoff_receipts(event_id,organization_id,conversation_id) values(p_event_id,p_organization_id,target.id);
    return target.id;
  end if;
  update public.conversations set status = 'active' where id = target.id and status = 'closed';
  if (p_agent_id is null) = (p_routing_queue_id is null) then
    raise exception 'exactly one handoff target is required' using errcode = '23514';
  end if;
  if p_routing_queue_id is not null then
    perform public.route_conversation_to_queue(target.id, p_routing_queue_id);
  else
    if not exists (select 1 from public.agents a where a.organization_id = p_organization_id
      and a.id = p_agent_id and not a.ai and a.user_id is not null
      and coalesce(a.extra->'invitation'->>'status', 'accepted') = 'accepted') then
      raise exception 'handoff requires an active tenant human agent' using errcode = '23514';
    end if;
    -- Reuse assignment constraints; clear old queue so a valid tenant agent
    -- isn't incorrectly rejected as a member of a previous routing queue.
    update public.conversations set routing_queue_id = null,
      assigned_agent_id = case when
        (public.business_hours_status(p_organization_id,null,p_agent_id)->>'configured')::boolean
        and public.business_hours_status(p_organization_id,null,p_agent_id)->>'reason'<>'available'
        then null else p_agent_id end where id = target.id;
    perform public.notify_support_unavailability(target.id,p_event_id::text,p_agent_id);
  end if;
  insert into public.chatbot_node_conversations(organization_id, organization_address, node_conversation_id, conversation_id, ownership_revision, lifecycle_enabled)
    values (p_organization_id, p_organization_address, p_node_conversation_id, target.id, coalesce(p_revision,'0'), p_revision is not null)
    on conflict (organization_id, organization_address, node_conversation_id)
    do update set human_owned = true, state = 'human_owned', ownership_revision = coalesce(p_revision,chatbot_node_conversations.ownership_revision),
      lifecycle_enabled = chatbot_node_conversations.lifecycle_enabled or p_revision is not null;
  insert into public.chatbot_node_handoff_receipts(event_id, organization_id, conversation_id)
    values(p_event_id, p_organization_id, target.id);
  return target.id;
end;
$function$
;

CREATE OR REPLACE FUNCTION public.record_node_support_request(p_organization_id uuid, p_address text, p_recipient text, p_node_conversation_id text, p_event_id uuid, p_revision text, p_support_request jsonb)
 RETURNS uuid
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO ''
AS $function$
declare
  target public.conversations;
  mapping public.chatbot_node_conversations;
  receipt public.chatbot_node_handoff_receipts;
  queue_id uuid;
  agent_id uuid;
begin
  perform pg_advisory_xact_lock(hashtextextended(p_event_id::text,117));
  select * into receipt from public.chatbot_node_handoff_receipts where event_id = p_event_id;
  if found then
    if receipt.organization_id <> p_organization_id then raise exception 'event belongs to another tenant' using errcode='42501'; end if;
    return receipt.conversation_id;
  end if;
  if not public.is_organization_active(p_organization_id) or not public.is_node_managed_number(p_organization_id,p_address) then
    raise exception 'tenant or Node binding unavailable' using errcode='42501'; end if;
  if p_revision !~ '^[0-9]+$' or p_support_request->>'status' is distinct from 'waiting'
    or p_support_request->>'id' is null or p_support_request->>'source_wamid' is null then
    raise exception 'invalid support request' using errcode='22023'; end if;
  perform (p_support_request->>'id')::uuid;
  select c.* into target from public.conversations c join public.messages m on m.conversation_id=c.id
    where c.organization_id=p_organization_id and c.organization_address=p_address and c.contact_address=p_recipient
      and m.organization_id=p_organization_id and m.external_id=p_support_request->>'source_wamid' and m.direction='incoming'
    for update of c;
  if not found then raise exception 'source message has not arrived' using errcode='40001'; end if;
  select * into mapping from public.chatbot_node_conversations where organization_id=p_organization_id
    and organization_address=p_address and node_conversation_id=p_node_conversation_id for update;
  if found and mapping.conversation_id <> target.id then raise exception 'conversation mapping mismatch' using errcode='23514'; end if;
  -- A newer bot snapshot can arrive before the request's independent outbox
  -- event. Route that same waiting request once; never revive a handled request.
  if mapping.lifecycle_enabled and p_revision::numeric <= mapping.ownership_revision::numeric
    and not (mapping.support_request->>'id'=p_support_request->>'id' and mapping.support_request->>'status'='waiting') then
    insert into public.chatbot_node_handoff_receipts(event_id,organization_id,conversation_id) values(p_event_id,p_organization_id,target.id);
    return target.id;
  end if;
  if mapping.human_owned and mapping.lifecycle_enabled then raise exception 'conversation already human owned' using errcode='40001'; end if;
  if mapping.support_request->>'status'='waiting' and mapping.support_request->>'id' <> p_support_request->>'id' then
    raise exception 'another support request is pending' using errcode='23514'; end if;
  if mapping.pending_request_id is not null then raise exception 'conversation synchronization pending' using errcode='40001'; end if;
  queue_id := (p_support_request->'target'->>'routing_queue_id')::uuid;
  agent_id := (p_support_request->'target'->>'agent_id')::uuid;
  if (queue_id is null) = (agent_id is null) then raise exception 'exactly one support target required' using errcode='23514'; end if;
  update public.conversations set status='active' where id=target.id and status='closed';
  if queue_id is not null then perform public.route_conversation_to_queue(target.id,queue_id);
  else
    if not exists(select 1 from public.agents where id=agent_id and organization_id=p_organization_id and not ai and user_id is not null
      and coalesce(extra->'invitation'->>'status','accepted')='accepted') then raise exception 'accepted tenant agent required' using errcode='23514'; end if;
    update public.conversations set routing_queue_id=null,
      assigned_agent_id=case when
        (public.business_hours_status(p_organization_id,null,agent_id)->>'configured')::boolean
        and public.business_hours_status(p_organization_id,null,agent_id)->>'reason'<>'available'
        then null else agent_id end where id=target.id;
    perform public.notify_support_unavailability(target.id,p_support_request->>'id',agent_id);
  end if;
  insert into public.chatbot_node_conversations(organization_id,organization_address,node_conversation_id,conversation_id,
    human_owned,lifecycle_enabled,ownership_revision,state,support_request,last_inbound_wamid)
    values(p_organization_id,p_address,p_node_conversation_id,target.id,false,true,p_revision,'bot_ready',p_support_request,p_support_request->>'source_wamid')
    on conflict(organization_id,organization_address,node_conversation_id) do update set
      human_owned=false,lifecycle_enabled=true,ownership_revision=greatest(p_revision::numeric,chatbot_node_conversations.ownership_revision::numeric)::text,
      state='bot_ready',support_request=p_support_request;
  insert into public.chatbot_node_handoff_receipts(event_id,organization_id,conversation_id) values(p_event_id,p_organization_id,target.id);
  return target.id;
end;
$function$
;

CREATE OR REPLACE FUNCTION public.route_conversation_to_queue(p_conversation_id uuid, p_routing_queue_id uuid)
 RETURNS conversations
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO ''
AS $function$
declare
  target_conversation public.conversations;
  destination_queue public.routing_queues;
  previous_routing_queue_id uuid;
  previous_queue_name text;
  route_time timestamp with time zone := now();
begin
  select conversation.* into target_conversation
  from public.conversations conversation
  where conversation.id = p_conversation_id
  for update;

  if not found then
    raise exception using
      errcode = 'P0002',
      message = 'conversation not found';
  end if;

  if target_conversation.status <> 'active' then
    raise exception using
      errcode = '23514',
      message = 'only active conversations can be routed';
  end if;

  select queue.* into destination_queue
  from public.routing_queues queue
  where queue.id = p_routing_queue_id
    and queue.organization_id = target_conversation.organization_id
    and queue.status = 'active';

  if not found then
    raise exception using
      errcode = '23514',
      message = 'routing destination must be an active queue in the same organization';
  end if;

  previous_routing_queue_id := target_conversation.routing_queue_id;

  if previous_routing_queue_id is not null then
    select queue.name into previous_queue_name
    from public.routing_queues queue
    where queue.id = previous_routing_queue_id
      and queue.organization_id = target_conversation.organization_id;
  end if;

  update public.conversations conversation
  set routing_queue_id = p_routing_queue_id,
      routed_at = route_time,
      assigned_agent_id = null
  where conversation.id = p_conversation_id
  returning * into target_conversation;

  insert into public.conversation_routing_events (
    organization_id,
    conversation_id,
    previous_routing_queue_id,
    previous_routing_queue_name,
    destination_routing_queue_id,
    destination_routing_queue_name,
    actor_agent_id,
    source,
    explanation,
    created_at
  ) values (
    target_conversation.organization_id,
    target_conversation.id,
    previous_routing_queue_id,
    previous_queue_name,
    destination_queue.id,
    destination_queue.name,
    null,
    'chatbot_handoff',
    null,
    route_time
  );

  target_conversation := public.try_auto_assign_conversation(
    target_conversation.id,
    'chatbot_handoff'
  );

  perform public.notify_support_unavailability(target_conversation.id,
    'route:' || route_time::text);

  return target_conversation;
end;
$function$
;

CREATE OR REPLACE FUNCTION public.try_auto_assign_conversation(p_conversation_id uuid, p_source text DEFAULT 'recovery'::text)
 RETURNS conversations
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO ''
AS $function$
declare
  conversation_row public.conversations;
  queue_row public.routing_queues;
  selected_agent public.agents;
  last_agent_id uuid;
  assignment_time timestamptz := clock_timestamp();
  assignment_event_id uuid;
begin
  select c.* into conversation_row
  from public.conversations c
  where c.id = p_conversation_id
  for update;

  if not found or conversation_row.status <> 'active'
    or conversation_row.assigned_agent_id is not null
    or conversation_row.routing_queue_id is null then
    return conversation_row;
  end if;

  if not public.is_organization_active(conversation_row.organization_id) then
    return conversation_row;
  end if;

  select q.* into queue_row
  from public.routing_queues q
  join public.organization_automation_settings settings
    on settings.organization_id = q.organization_id
   and settings.auto_assign_conversations
  where q.organization_id = conversation_row.organization_id
    and q.id = conversation_row.routing_queue_id
    and q.status = 'active'
    and q.assignment_strategy = 'round_robin';

  if not found then return conversation_row; end if;

  if not (public.business_hours_status(conversation_row.organization_id,
      conversation_row.routing_queue_id, null, assignment_time)->>'open')::boolean then
    return conversation_row;
  end if;

  insert into public.routing_queue_assignment_state (
    organization_id, routing_queue_id
  ) values (conversation_row.organization_id, queue_row.id)
  on conflict (organization_id, routing_queue_id) do nothing;

  select state.last_assigned_agent_id into last_agent_id
  from public.routing_queue_assignment_state state
  where state.organization_id = conversation_row.organization_id
    and state.routing_queue_id = queue_row.id
  for update;

  with eligible as (
    select a.*, row_number() over (order by member.created_at, a.id) as position
    from public.routing_queue_members member
    join public.agents a
      on a.organization_id = member.organization_id and a.id = member.agent_id
    join public.agent_assignment_presence presence
      on presence.organization_id = a.organization_id and presence.agent_id = a.id
    where member.organization_id = conversation_row.organization_id
      and member.routing_queue_id = queue_row.id
      and a.ai = false and a.user_id is not null
      and a.extra->>'role' = 'agent'
      and coalesce(a.extra->'invitation'->>'status', 'accepted') = 'accepted'
      and presence.available
      and presence.last_heartbeat_at >= assignment_time - interval '2 minutes'
  ), cursor_position as (
    select position from eligible where id = last_agent_id
  )
  select e.organization_id, e.user_id, e.id, e.name, e.picture, e.ai,
         e.extra, e.created_at, e.updated_at
  into selected_agent
  from eligible e
  order by
    case when e.position > coalesce((select position from cursor_position), 0) then 0 else 1 end,
    e.position
  limit 1;

  if not found then return conversation_row; end if;

  update public.conversations c
  set assigned_agent_id = selected_agent.id
  where c.id = conversation_row.id
  returning * into conversation_row;

  update public.routing_queue_assignment_state state
  set last_assigned_agent_id = selected_agent.id, updated_at = assignment_time
  where state.organization_id = conversation_row.organization_id
    and state.routing_queue_id = queue_row.id;

  insert into public.conversation_assignment_events (
    organization_id, conversation_id, routing_queue_id, routing_queue_name,
    assigned_agent_id, assigned_agent_name, strategy, source, created_at
  ) values (
    conversation_row.organization_id, conversation_row.id, queue_row.id, queue_row.name,
    selected_agent.id, selected_agent.name, 'round_robin', p_source, assignment_time
  ) returning id into assignment_event_id;

  insert into public.messages (
    organization_id, conversation_id, direction, agent_id, service,
    organization_address, group_address, content, status, timestamp
  ) values (
    conversation_row.organization_id, conversation_row.id, 'internal', null,
    conversation_row.service, conversation_row.organization_address,
    conversation_row.group_address,
    jsonb_build_object(
      'version', '1', 'type', 'text', 'kind', 'assignment_event',
      'text', format('Automatically assigned to %s using Round Robin.', selected_agent.name),
      'assignment_event', jsonb_build_object(
        'id', assignment_event_id, 'agent_id', selected_agent.id,
        'agent_name', selected_agent.name, 'queue_id', queue_row.id,
        'queue_name', queue_row.name, 'strategy', 'round_robin', 'source', p_source
      )
    ), '{}'::jsonb, assignment_time
  );

  perform public.enqueue_user_notification(
    conversation_row.organization_id, selected_agent.id, null,
    conversation_row.id, 'conversation_assigned',
    format('automatic_assignment:%s', assignment_event_id),
    jsonb_build_object(
      'assignment_event_id', assignment_event_id,
      'assigned_agent_id', selected_agent.id,
      'routing_queue_id', queue_row.id,
      'routing_queue_name', queue_row.name,
      'strategy', 'round_robin'
    )
  );

  return conversation_row;
end;
$function$
;

CREATE OR REPLACE FUNCTION public.validate_business_hours_schedule(p_schedule jsonb)
 RETURNS void
 LANGUAGE plpgsql
 STABLE
 SET search_path TO ''
AS $function$
declare d text; r jsonb; h jsonb; dates text[] := '{}';
begin
  if jsonb_typeof(p_schedule) is distinct from 'object'
    or p_schedule->>'mode' not in ('all_days','per_day')
    or p_schedule->>'mode' is null
    or not exists(select 1 from pg_catalog.pg_timezone_names where name=p_schedule->>'timezone')
    or (p_schedule ? 'enabled' and jsonb_typeof(p_schedule->'enabled') <> 'boolean')
    or jsonb_typeof(p_schedule->'per_day') is distinct from 'object' then
    raise exception 'Invalid business hours mode or time zone' using errcode='22023';
  end if;
  foreach d in array array['all_days','monday','tuesday','wednesday','thursday','friday','saturday','sunday'] loop
    r := case when d='all_days' then p_schedule->d else p_schedule->'per_day'->d end;
    if jsonb_typeof(r) is distinct from 'object'
      or coalesce(r->>'start_time','') !~ '^([01][0-9]|2[0-3]):(00|15|30|45)$'
      or coalesce(r->>'end_time','') !~ '^(([01][0-9]|2[0-3]):(00|15|30|45)|24:00)$'
      or (d<>'all_days' and jsonb_typeof(r->'enabled') is distinct from 'boolean') then
      raise exception 'Invalid business hours time range: %',d using errcode='22023';
    end if;
    if ((d='all_days' and p_schedule->>'mode'='all_days')
      or (d<>'all_days' and p_schedule->>'mode'='per_day' and (r->>'enabled')::boolean))
      and r->>'end_time' <= r->>'start_time' then
      raise exception 'End time must be after start time: %',d using errcode='22023';
    end if;
  end loop;
  if p_schedule ? 'holidays' then
    if jsonb_typeof(p_schedule->'holidays') <> 'array' or jsonb_array_length(p_schedule->'holidays') > 366 then
      raise exception 'At most 366 holiday overrides are allowed' using errcode='22023'; end if;
    for h in select value from jsonb_array_elements(p_schedule->'holidays') loop
      if coalesce(h->>'date','') !~ '^[0-9]{4}-[0-9]{2}-[0-9]{2}$'
        or jsonb_typeof(h->'closed') is distinct from 'boolean' then
        raise exception 'Invalid holiday date or closed flag' using errcode='22023'; end if;
      perform (h->>'date')::date;
      if h->>'date'=any(dates) then raise exception 'Duplicate holiday date' using errcode='22023'; end if;
      dates := array_append(dates,h->>'date');
      if not (h->>'closed')::boolean and (
        coalesce(h->>'start_time','') !~ '^([01][0-9]|2[0-3]):(00|15|30|45)$'
        or coalesce(h->>'end_time','') !~ '^(([01][0-9]|2[0-3]):(00|15|30|45)|24:00)$'
        or h->>'end_time' <= h->>'start_time') then
        raise exception 'Invalid holiday opening hours' using errcode='22023'; end if;
    end loop;
  end if;
end;
$function$
;

CREATE TRIGGER zz_validate_business_hours BEFORE INSERT OR UPDATE OF extra ON public.organizations FOR EACH ROW EXECUTE FUNCTION guard_business_hours_settings();

revoke all on function public.validate_business_hours_schedule(jsonb) from public,anon,authenticated;
revoke all on function public.guard_business_hours_settings() from public,anon,authenticated;
revoke all on function public.business_hours_schedule_open(jsonb,timestamptz) from public,anon,authenticated;
revoke all on function public.business_hours_status(uuid,uuid,uuid,timestamptz) from public,anon,authenticated;
revoke all on function public.notify_support_unavailability(uuid,text,uuid) from public,anon,authenticated;
revoke all on function public.get_business_hours_status(uuid,uuid) from public,anon;
grant execute on function public.get_business_hours_status(uuid,uuid) to authenticated,service_role;
grant execute on function public.business_hours_status(uuid,uuid,uuid,timestamptz) to service_role;
